language: python
python:
      - '3.8.5'

branches:
  only:
      - main 

env:        
      - DJANGO_SETTINGS_MODULE="projet_13.settings.travis"

services: 
      - postgresql

script:
      - ./manage.py test