language: python
python:
      - '3.8.5'

before_script:
      - pip install -r requirements.txt

branches:
  only:
      - main

env:
  gobal:            
      - DJANGO_SETTINGS_MODULE="projet_13.settings.travis"
      - secure : "vnfwdVYCse9hRD/S0x69S5A7rgi7TQ1QEcqbLXeDsIw5YgIheD1kJLefCLqEucM4wpdTKC7ycMyya9WvxlZUggZx0beQz5BCSulDc0DBFLC+yw87UW9qWDh7hwwByqlTBgaXo+gpWaxmyt/JC9ET7cQpkERgACQrvP4xYf5spy6rQ6Cu6yfXBZWu7EwW5BoL+rFjrwsOBYYlABhgfbu+yhqhDOmMoi9m0l4PrU5W3xnlBOJaqxOUc0zrNPHM3jNxz4T/Y+6kqn1Rp+FZPFn5UiECFfzCafV3Al7WxxNQDfJR61R1eAGhVQ9hbesEgSaV1iW69STcCkG+N96hXVfpQGUtz5Zru/FEO4ff1vV/sZ6fPk5T2WF9JuLa/xqJyrpf+MgnrZwzGH7L4aEXS10v2FhygfqKJt6amHaumqolVCmhUHXVavUhdNum9uD4+e8iup0IQFmtVVGxCtFvgKDIB6xGvrYLOydnOSKcmB9kLoFgPWyw5eVBYWNQQZtLQ3GlBT5zs9TqxKzfPjntfv7vuAUHl8p4Q8x/IXEw08frC/mwqRzSFI7q++VMGTxv52+AnUO1CxeAo+dKfyOy5LczCUh4/uk5Lht32SN0MrlNVqw+mp26jy2eYYhlSXnEy4wfsvh2mwvwpKUkVd2V8vd1jBhBsLSbYH513LgrBO5v22E="


services: 
      - postgresql

script:
      - ./manage.py test