language: python
python:
      - '3.8.5'

before_script:
      - pip install -r requirements.txt

branches:
  only:
      - main

env:        
      - DJANGO_SETTINGS_MODULE="projet_13.settings.travis"
      - SECRET_KEY=randomzelriufm1694687946

services: 
      - postgresql

script:
      - ./manage.py test