PLACES = {
    "restaurant": "Restaurants",
    "supermarket": "Supermarchés",
    "bakery": "Boulangeries",
    "art_gallery": "Galeries d'art",
    "bicycle_store": "Magasins de vélos",
    "book_store": "Magasin de livres",
    "cafe": "Cafés",
    "church": "Eglise",
    "dentist": "Dentistes",
    "bar": "Bars",
    "hair_care": "Coiffeurs",
    "accounting": "Comptables",
    "aquarium": "Aquariums",
    "beauty_salon": "Salons de beauté",
    "doctor": "Médecins",
}
