# Generated by Django 3.2.3 on 2021-05-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20210530_1553"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="product",
            new_name="place",
        ),
    ]
